name: Athena
version: '0.0.0'
main: fr.kayrouge.athena.bukkit.BukkitAthena
api-version: '1.21'
authors: [ Kayrouge, Oxozot ]
commands:
  athena:
    description: give info about Athena
  furnaces:
    permission: athena.commands.furnaces
    description: donne un four
  artifacts:
    description: give an artifact to the use
  devworld:
    description: switch between world
  home:
    description: tp to a home
  sethome:
    description: set a home